# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  Docker:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v2
      
       - name: Login to Docker Hub
         uses: docker/login-action@v1
         with: 
           username: ${{ secrets.DOCKER_HUB_USERNAME }}
           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
           
       - name: Set up Docker Buildx
         id: buildx
         uses: docker/setup-buildx-action@v1
      
       - name: Build and push
         id: docker_build
         uses: docker/build-push-action@v2
         with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/flask_app:latest
      
       - name: Image digest
         run: |
           echo ${{steps.docker_build.outputs.digest }}
           exit 1
  
  Check:
     runs-on: ubuntu-latest
     needs: Docker
     steps:
       - if: ${{ success() }}
         uses: appleboy/telegram-action@master
         with:
               to: ${{ secrets.TELEGRAM_TO }}
               token: ${{ secrets.TELEGRAM_TOKEN }}
               message: The build was a success!
       - if: ${{ failure() }}
         uses: appleboy/telegram-action@master
         with:
               to: ${{ secrets.TELEGRAM_TO }}
               token: ${{ secrets.TELEGRAM_TOKEN }}
               message: The build was a fail!
